### ISSUE TITLE
Registro fallido en ServicioRegistradorNotificacion

### ISSUE THREAD

**Issue by adwher** [kuic-sena/servidor#10]
Cuando se realiza el envío para registrar una notificación, el servicio colapsa puesto que no se tiene en cuenta el hecho de que el campo `texto` de la tabla **Notificación** de la base de datos es no nulo, y cuando se realiza el registro por medio del servicio, el formulario denominado `FormularioRegistrarNotificacion` no posee un campo para el texto por lo que al enviar el registro a la base de datos, el campo texto queda nulo.

## Sugerencia

Cambiar la clase `FormularioRegistrarNotificacion`, agregando el campo de texto o contenido del mensaje, para lo cual se sugiere lo siguiente:

```cs
public string Mensaje { get; set; }
```

Agregar el campo agregado a las opciones cuando se registra una nueva notificación en base al formulario.

```cs
nuevaNotificacion.Texto = formulario.Mensaje;
```

**Comment by lorenacuadros** [comment]
Se solventó el error, actualizando el servicio y los controladores
