### ISSUE TITLE
Error de sintaxis en insertar Cliente

### ISSUE THREAD

**Issue by adwher** [kuic-sena/servidor#4]
En el repositorio de cliente, se esta realizando un `insert` sin el nombre de la tabla. Se debe agregar el nombre en la consulta realizada en la linea 38 del `RepoCliente` antes de los atributos que se van a insertar.

Sugerencia:

```sql
insert into cliente (nombre, encargado, rut, correo, direccion, telefono) 
values (@Nombre, @Encargado, @Rut, @Correo, @Direccion, @Telefono)
```

**Comment by MiNeaLoPega** [comment]
Listongo v:
