### ISSUE TITLE
Registro incompleto en producto

### ISSUE THREAD

**Issue by adwher** [kuic-sena/servidor#7]
Cuando se realiza el registro de un nuevo producto, se permite el paso de códigos menores a 5 caracteres y no se coloca una categoría por defecto; aparte de que la interfaz no está terminada y se ve desorganizada, junto a la característica de que los botones no le indican al usuario que se está realizando el proceso de registro (esto se puede mejorar colocando una animación de carga en los botones).

**Comment by lorenacuadros** [comment]
Queda pendiente la parte de que se elija una categoría por defecto.

**Comment by adwher** [comment]
> Queda pendiente la parte de que se elija una categoría por defecto.

Esa parte ya quedó solventada con la actualización en los componentes: `SelectField` y utilizando el atributo `Range` en el campo de esa clase.
