### ISSUE TITLE
Quitar la funcionalidad de eliminar una entrada

### ISSUE THREAD

**Issue by adwher** [kuic-sena/servidor#8]
Se necesita quitar toda funcionalidad de eliminar una entrada, para lo cual se sugiere empezar por las siguientes piezas:

1. Eliminar la clase `ServicioEliminadorEntrada`.
2. La ruta de eliminar en el controlador `EntradaController`.
3. Remover la funcionalidad de eliminar de la vista `TarjetaEntrada`.

**Comment by lorenacuadros** [comment]
La funcionalidad de "eliminar entrada" fue descartada exitosa mente en el commit que se ha dejado para solventarlo
